# Config options adapted for local development

baseurl: "/delft-meta-research-lab" # the subpath of your site, e.g. /blog
url: "http://localhost" # the base hostname & protocol for your site, e.g. http://example.com
